[project]
name = "flickpicks_api"
version = "0.1"
dependencies = [
    "beanie",
    "fastapi",
    "motor",
    "pydantic",
    "uvicorn",
    "python-jose[cryptography]",
    "httpx",
    "modal-client",
    "Svix",
]

[project.scripts]
start_dev_api = "flickpicks_api.main:start"